L1_WETH_ADDR = ""
L1_PROXY_ADMIN_ADDR = "0xF073a49bC8Ec2Ee218968be66cf29f924697e2bd"
L1_PROXY_IMPLEMENTATION_PLACEHOLDER_ADDR = "0x62c3Ced16eE242E4D45416bC0B365F820b71739e"
L1_WHITELIST_ADDR = "0x55764a23F118A4CA66Ea97ffcCa8348AAC6A047E"
L1_SCROLL_CHAIN_PROXY_ADDR = "0x5c64ad84B7DC6E45BdEBbE5193787Ab893514FC7"
L1_SCROLL_MESSENGER_PROXY_ADDR = "0xB8BD4E103F461a613E220E83932a350F73085bDA"
L1_MESSAGE_QUEUE_V1_IMPLEMENTATION_ADDR = "0x4393B9195158566e9f7fAB4519BDb4e496cE5989"
L1_MESSAGE_QUEUE_V1_PROXY_ADDR = "0xedeE3b3009Bb66948A6152aFA340c9D385D29f3E"
L1_MESSAGE_QUEUE_V2_IMPLEMENTATION_ADDR = "0x86ec91688Fc357e5188409b4e3e98054b47c8ea2"
L1_MESSAGE_QUEUE_V2_PROXY_ADDR = "0x41544cE3Bb903c8b21FFaE3B8A2c6722787063F2"
L1_ENFORCED_TX_GATEWAY_IMPLEMENTATION_ADDR = "0x4b69F2A12FE165939eaF55dA1f3a8F9af7Bc0d31"
L1_ENFORCED_TX_GATEWAY_PROXY_ADDR = "0x09753595Fc91aC441E3D49048EA780843a4c72ca"
L1_PLONK_VERIFIER_ADDR = "0xB00B09CE14812932afAE4e97D03c48b18FB878e9"
L1_ZKEVM_VERIFIER_V2_ADDR = "0x825176A2F2566a68bF23DA8929a74887015fDA99"
L1_MULTIPLE_VERSION_ROLLUP_VERIFIER_ADDR = "0x13C03cba4C25807e23e56C1895C23B00df093610"
L1_SCROLL_CHAIN_IMPLEMENTATION_ADDR = "0x05833514D05d4f343020f1ed5Eed5b080A4cfBFC"
L1_GATEWAY_ROUTER_IMPLEMENTATION_ADDR = "0xA1b6B28914bD608b85792fDE16d1A914729a62Eb"
L1_GATEWAY_ROUTER_PROXY_ADDR = "0xa5Aab9141f248c19Bd5Db23bd30372d47C361223"
L1_ETH_GATEWAY_PROXY_ADDR = "0xB871794762fd294B0a84Dd75e03c6E3F39Fe337b"
L1_WETH_GATEWAY_PROXY_ADDR = "0xA199F6628dE78849D1Bb119D2a5764e78e2E9c07"
L1_STANDARD_ERC20_GATEWAY_PROXY_ADDR = "0x8b075C23c6C45489D8Db9B3B726B6f0f2ba7fEb7"
L1_CUSTOM_ERC20_GATEWAY_PROXY_ADDR = "0xfeBb0bd88ADdA433FE4BC191BC3794cca4F9B5FE"
L1_ERC721_GATEWAY_PROXY_ADDR = "0xbE5aB8CfB2B60279c30bD74Aa3a28fB063abF0DF"
L1_ERC1155_GATEWAY_PROXY_ADDR = "0xc2699AC5d3Df3E00C3EBd1a290a6490b822C1549"
L2_MESSAGE_QUEUE_ADDR = "0x5300000000000000000000000000000000000000"
L1_GAS_PRICE_ORACLE_ADDR = "0x5300000000000000000000000000000000000002"
L2_WHITELIST_ADDR = "0x5300000000000000000000000000000000000003"
L2_WETH_ADDR = ""
L2_TX_FEE_VAULT_ADDR = "0x5300000000000000000000000000000000000005"
L2_PROXY_ADMIN_ADDR = "0xbAE1c838C812705A60B0450A22961C6b1221Bb21"
L2_PROXY_IMPLEMENTATION_PLACEHOLDER_ADDR = "0x5eE73D06023e985d91F5EaA1b9b34566357e6843"
L2_SCROLL_MESSENGER_PROXY_ADDR = ""
L2_ETH_GATEWAY_PROXY_ADDR = "0x861f25a798583b5c9ee1d57B6d1e3a904D10fc11"
L2_WETH_GATEWAY_PROXY_ADDR = "0xDEBD44BaFC4564c2281617dbAdc75665c225d3e0"
L2_STANDARD_ERC20_GATEWAY_PROXY_ADDR = "0x880Ca608F916E34ec2036fBB7f3a76365C4192B5"
L2_CUSTOM_ERC20_GATEWAY_PROXY_ADDR = "0xEb98B9bdb54f8Eb10ae7b62f88d8d26BbF16ae06"
L2_ERC721_GATEWAY_PROXY_ADDR = "0xB16b498a86F157F39EB44eb4B26794aA49bd46d1"
L2_ERC1155_GATEWAY_PROXY_ADDR = "0x768e33cC8520392156FB09f2Ec3fD8d3c46d733F"
L2_SCROLL_STANDARD_ERC20_ADDR = "0x14a437236E7a85b344DdDe73bDB4fE743422F576"
L2_SCROLL_STANDARD_ERC20_FACTORY_ADDR = "0x541F00A99eF14227A344c9223E9BE4F3ED263187"
L1_SCROLL_MESSENGER_IMPLEMENTATION_ADDR = "0xd47D5cD21Dc57304D16FA7D2cbFf9BAc379c3F97"
L1_STANDARD_ERC20_GATEWAY_IMPLEMENTATION_ADDR = "0x41b239d74d6e59fA4604fD60c2a9162C1fA2f5C3"
L1_ETH_GATEWAY_IMPLEMENTATION_ADDR = "0x4daa18e4ff71ebcbC7Dfb251917E1263972b2a36"
L1_WETH_GATEWAY_IMPLEMENTATION_ADDR = "0x8160aA244013fCaE7DbcC6D6dB12Db6F1e53A92e"
L1_CUSTOM_ERC20_GATEWAY_IMPLEMENTATION_ADDR = "0xdAb297E5B5A7320f906d3088708Df548a1033e25"
L1_ERC721_GATEWAY_IMPLEMENTATION_ADDR = "0x7F39Ae375a131A415A05FBD8d46e5Bd6F5f3578d"
L1_ERC1155_GATEWAY_IMPLEMENTATION_ADDR = "0x26f58942946d3e2ec638C64a3a25Ee69319c76AF"
L2_SCROLL_MESSENGER_IMPLEMENTATION_ADDR = ""
L2_GATEWAY_ROUTER_IMPLEMENTATION_ADDR = "0x0e15A5839EE68cEEa1Ae35F63F5F415c55FAB731"
L2_GATEWAY_ROUTER_PROXY_ADDR = "0x07C9821495f7d28526331971652D669A2E361618"
L2_STANDARD_ERC20_GATEWAY_IMPLEMENTATION_ADDR = "0xfc629eb4BB98Bf354E33C4652271f24eEeedEF3d"
L2_ETH_GATEWAY_IMPLEMENTATION_ADDR = "0xE9E69ac9CC6b928059d6FA89CE46112d566664f0"
L2_WETH_GATEWAY_IMPLEMENTATION_ADDR = "0x90294Ac83b79bde23CA9144532B2840fDFc24C6D"
L2_CUSTOM_ERC20_GATEWAY_IMPLEMENTATION_ADDR = "0x72d364a93E5C1f7d0944f6bfD145355e7A3150f5"
L2_ERC721_GATEWAY_IMPLEMENTATION_ADDR = "0xE77037fC7ed332857723c97529a4d457a348a1E9"
L2_ERC1155_GATEWAY_IMPLEMENTATION_ADDR = "0x6F8264Cf313F20DA2721fF1A86c01F7754c6e432"
L1_SYSTEM_CONFIG_IMPLEMENTATION_ADDR = "0x18B99289fa325c5dEe67a151f699de30963721dD"
L1_SYSTEM_CONFIG_PROXY_ADDR = "0x2aB9e1aaEe8926eD659A740B27f976994d04AeD9"
L1_WDOGE_ADDR = "0xF853cEA14b2fE81b840a3CF9456dfeCa9be9a273"
L1_WRAPPED_TOKEN_GATEWAY_ADDR = ""
L2_BASCULE_MOCK_VERIFIER_ADDR = "0xe68F95f05a9493cc98b9908b4cdC757a4B343796"
L2_DOGEOS_MESSENGER_IMPLEMENTATION_ADDR = "0x1578E17fbe36CB7717DCf67f18A5E9F41756826F"
L2_DOGEOS_MESSENGER_PROXY_ADDR = "0xA0e17A64E4c5885bbA2EE189652A73f414C0f814"
L2_MOAT_IMPLEMENTATION_ADDR = "0x368e0550Fc0A06dAED24C34606fb1D2Ee2494484"
L2_MOAT_PROXY_ADDR = "0x85070ad802E5f296AFb4d83340127Dbe4aD9c25C"
L2_WDOGE_ADDR = "0x628bEb8C034C873bbC5cEB62c3e2F1657e62d78d"
L2_WDOGE_GATEWAY_IMPLEMENTATION_ADDR = ""
L2_WDOGE_GATEWAY_PROXY_ADDR = ""
