name: Build and publish scroll-alpine image
# This workflow aims to build images from the feat-deterministic-deployment branch

on:
  workflow_dispatch:

jobs:
  build:
    name: Clone, Build, Publish
    runs-on: ubuntu-latest
    permissions: {}

    steps:
      - name: Check out repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          submodules: true
          persist-credentials: false

      - name: Update submodules recursively
        run: git submodule update --init --recursive

      - name: Set up QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3.7.0

      - name: Setup Node.js environment
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: '21'
          package-manager-cache: false

      - name: Install dependencies
        run: npm install

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0
        with:
          cache-binary: false

      - name: Login to Dockerhub
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef #v3.6.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build deploy image
        id: build_deploy_image
        env:
          REPOSITORY: scrolltech/scroll-stack-contracts
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          context: .
          file: docker/Dockerfile.deploy
          tags: |
            ${{ env.REPOSITORY }}:deploy-${{ github.sha }}

      - name: Build gen image
        id: build_gen_image
        env:
          REPOSITORY: scrolltech/scroll-stack-contracts
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          context: .
          file: docker/Dockerfile.gen-configs
          tags: |
            ${{ env.REPOSITORY }}:gen-configs-${{ github.sha }}
