name: Build and publish scroll-alpine image
# This workflow aims to build images from the feat-deterministic-deployment branch

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Clone, Build, Publish
    runs-on: ubuntu-latest
    permissions: {}
    env:
      DOCKER_REPOSITORY: dogeos69/scroll-stack-contracts

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: true
          persist-credentials: false

      - name: Update submodules recursively
        run: git submodule update --init --recursive

      - name: Set image tag
        id: set_tag
        env:
          EVENT_NAME: ${{ github.event_name }}
          REF_TYPE: ${{ github.ref_type }}
          REF_NAME: ${{ github.ref_name }}
          SHA: ${{ github.sha }}
        run: |
          if [[ "$EVENT_NAME" == "push" && "$REF_TYPE" == "tag" ]]; then
            echo "IMAGE_TAG=$REF_NAME" >> $GITHUB_OUTPUT
          else
            echo "IMAGE_TAG=$SHA" >> $GITHUB_OUTPUT
          fi

      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '21'

      - name: Install dependencies
        run: npm install

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0
        with:
          cache-binary: false

      - name: Login to Dockerhub
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 #v3.4.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build base image
        id: build_base_image
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          context: .
          file: docker/Dockerfile.base
          tags: ${{ env.DOCKER_REPOSITORY }}:base-${{ steps.set_tag.outputs.IMAGE_TAG }}

      - name: Build deploy image
        id: build_deploy_image
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # v6.15.0
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          context: .
          file: docker/Dockerfile.deploy
          tags: ${{ env.DOCKER_REPOSITORY }}:deploy-${{ steps.set_tag.outputs.IMAGE_TAG }}
          build-args: |
            BASE_IMAGE=${{ env.DOCKER_REPOSITORY }}:base-${{ steps.set_tag.outputs.IMAGE_TAG }}

      - name: Build gen image
        id: build_gen_image
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # v6.15.0
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          context: .
          file: docker/Dockerfile.gen-configs
          tags: ${{ env.DOCKER_REPOSITORY }}:gen-configs-${{ steps.set_tag.outputs.IMAGE_TAG }}
          build-args: |
            BASE_IMAGE=${{ env.DOCKER_REPOSITORY }}:base-${{ steps.set_tag.outputs.IMAGE_TAG }}

      - name: Build verify image
        id: build_verify_image
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # v6.15.0
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          context: .
          file: docker/Dockerfile.verify
          tags: ${{ env.DOCKER_REPOSITORY }}:verify-${{ steps.set_tag.outputs.IMAGE_TAG }}
          build-args: |
            BASE_IMAGE=${{ env.DOCKER_REPOSITORY }}:base-${{ steps.set_tag.outputs.IMAGE_TAG }}
